### ISSUE TITLE
introduce directions to Ordering

### ISSUE THREAD

**Issue by normen662** [FoundationDB/fdb-record-layer#1318]
This is a follow up to #1142 which refactored the modeling of orderings to model interesting orderings as well as plan properties. One of the things that we didn't model at all so far is the directionality of the ordering as ordering is assumed to be forward or reversed on a global level. While that is true and as we change the modeling the directionality of the ordering should be captured (and used) within the new `Ordering` class.

**Comment by alecgrieser** [comment]
Was this resolved with #1474? It looks like `OrderingPart`s now have individual `reverse` fields, so we can model mixed-ordered-ness, though we can't actually plan queries with mixed ordering constraints yet.

**Comment by normen662** [comment]
It's not resolved unfortunately. The order direction is part of the modeling but at some stage we insist on all of them pointing in one direction. Also, these orderings do not partake in the matching just in the direction of a scan.
We need to have them be part of the actual matching as we need to understand that if the query wants `+a-b-c+d` we can do `+a-b-c+d` and then through reverse scanning `-a+b+c-d` but we would never match `+a+b+c+d`.
